# Copyright (c) 2019 NVIDIA CORPORATION. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:19.07-py3

FROM ${FROM_IMAGE_NAME}

RUN apt-get update && apt-get install -y pbzip2 pv bzip2 cabextract


ENV BERT_PREP_WORKING_DIR /workspace/bert/data

WORKDIR /opt 
RUN rm -rf /opt/pytorch/apex ; \ 
  git clone https://github.com/NVIDIA/apex.git pytorch/apex ; \ 
  cd pytorch/apex ; \ 
  pip uninstall --yes apex; \ 
  git checkout 880ab925bce9f817a93988b021e12db5f67f7787;  \ 
  git pull; \ 

pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

WORKDIR /workspace

RUN git clone https://github.com/attardi/wikiextractor.git

RUN git clone https://github.com/soskek/bookcorpus.git



WORKDIR /workspace/bert

RUN pip install tqdm boto3 requests six ipdb h5py html2text nltk progressbar


COPY . .


# download py 

RUN git clone https://github.com/NVIDIA/DeepLearningExamples.git
RUN cd DeepLearningExamples #&& git checkout pengwa/pt_nv_19.07
RUN cp DeepLearningExamples/PyTorch/LanguageModeling/BERT/* /workspace/bert -r

RUN chmod 777 /workspace/bert/ -R
